#!/bin/sh

down() {
light -U 3
brightness=$(light -g)
dunstify -a "BRIGHTNESS" "󰃠 decreasing to $brightness%" -h int:value:"$brightness" -i display-brightness-symbolic -r 2593 -u normal
}

up() {
light -A 3
brightness=$(light -g)
dunstify -a "BRIGHTNESS" "󰃠 increasing to $brightness%" -h int:value:"$brightness" -i display-brightness-symbolic -r 2593 -u normal
}

case "$1" in
  up) up;;
  down) down;;
esac
